### ISSUE TITLE
error filter must have a matching alias defined

### ISSUE THREAD

**Issue by cangsalak** [solomon-ochepa/codeigniter-modules#1]

**Comment by solomon-ochepa** [comment]
Hi, you didn't provide any description.

Please, tell us what you were doing before the error popped up, and also the error log.

**Comment by xloouch** [comment]
Hi i've got the same issue.. Created two modules.. one named "auth", the second called "api".

CodeIgniter Version 4.5.5 (latest)

here's the errors i get:
url: https://lore.ipsum/api

`
CRITICAL - 2024-10-08 13:40:21 --> CodeIgniter\Filters\Exceptions\FilterException: "auth" filter must have a matching alias defined.
[Method: GET, Route: api]
in SYSTEMPATH/Filters/Filters.php on line 495.
 1 SYSTEMPATH/Filters/Filters.php(495): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias()
 2 SYSTEMPATH/Filters/Filters.php(547): CodeIgniter\Filters\Filters->enableFilter()
 3 SYSTEMPATH/CodeIgniter.php(469): CodeIgniter\Filters\Filters->enableFilters()
 4 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
 5 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
 7 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb()
`

and secondly:
url: https://lore.ipsum/auth

`
CRITICAL - 2024-10-08 13:47:12 --> CodeIgniter\Filters\Exceptions\FilterException: "auth" filter must have a matching alias defined.
[Method: GET, Route: auth]
in SYSTEMPATH/Filters/Filters.php on line 495.
 1 SYSTEMPATH/Filters/Filters.php(495): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias()
 2 SYSTEMPATH/Filters/Filters.php(547): CodeIgniter\Filters\Filters->enableFilter()
 3 SYSTEMPATH/CodeIgniter.php(469): CodeIgniter\Filters\Filters->enableFilters()
 4 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
 5 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
 7 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb()
`

**Comment by xloouch** [comment]
I found it.. when you are using "shield" for authentication, you can remove the "['filter'=>"auth"] in the line

"$routes->group('', ['filter' => 'auth'], static function ($routes) {"

=> 
"$routes->group('', [], static function ($routes) {"

**Comment by solomon-ochepa** [comment]
> I found it.. when you are using "shield" for authentication, you can remove the "['filter'=>"auth"] in the line
> 
> "$routes->group('', ['filter' => 'auth'], static function ($routes) {"
> 
> => "$routes->group('', [], static function ($routes) {"

Hi, thank you so much. Can you submit a Pull Request if you don't mind?

**Comment by xloouch** [comment]
HI @solomon-ochepa 

sorry, I am not that experienced in github.

here's what i've changed

### filename: Commands/ModuleRoute.php
Line 116
Change

```php
\$routes->group('',  ['filter' => 'auth'], static function (\$routes) {
```

to

```php
\$routes->group('', [], static function (\$routes) {
```

In Addition, if you are not using the uuid-extension from "Michalsn\Uuid\UuidModel"
you need to change additionally

### filename: Commands/ModuleModel.php
Line 179
from

```php
use Michalsn\Uuid\UuidModel;
```

to

```php
#use Michalsn\Uuid\UuidModel;
```

and Line 118 & 119
from

```php
    protected \$uuidUseBytes     = false;
    protected \$uuidVersion      = 'uuid6';
```

to

```php
#    protected \$uuidUseBytes     = false;
#    protected \$uuidVersion      = 'uuid6';
```

**Comment by solomon-ochepa** [comment]
Thank you so much. Don't worry, I'll fix it ASAP.
